### ISSUE TITLE
Feature request: load instance specific emoji list

### ISSUE THREAD

**Issue by rubahness** [alicerunsonfedora/hyperspace#53] opened 2019-03-10 02:16 UTC
The Emoji picker only displays standard emoji, it would be good to have a list of the instance-specific emoji available to use

**Comment by alicerunsonfedora** [comment] 2019-03-10 02:17
I'm hoping to add this soon! (marking as a duplicate of #37 )

**Closed as completed by alicerunsonfedora** 2019-03-10 02:17 UTC
Labels: duplicate, enhancement
